# Generated by Django 3.1.5 on 2021-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото'),
        ),
    ]
