# Generated by Django 3.1.5 on 2021-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_check',
            field=models.CharField(default='', max_length=50, verbose_name='Проверка пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('mute', 'Mute'), ('user', 'User')], default='user', max_length=10, verbose_name='Статус пользователя'),
        ),
    ]
