# Generated by Django 3.1.5 on 2021-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210131_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_check',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Проверка пароля'),
        ),
    ]
