# Generated by Django 3.1.5 on 2021-01-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210131_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_check',
        ),
    ]
