version: '3.7'

services:
  web_news:
    build: .
    command: bash -c "python /usr/src/newspy/manage.py migrate && python /usr/src/newspy/manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/newspy
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_news
  db_news:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=news_python
      - POSTGRES_PASSWORD=news_python
      - POSTGRES_DB=db_news_python

volumes:
  postgres_data:
