version: '3.7'

services:
  db_news:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=news_python
      - POSTGRES_PASSWORD=news_python
      - POSTGRES_DB=db_news_python
  web_news:
    build: .
    command:
      - python /usr/src/newspy/manage.py migrate
      - python /usr/src/newspy/manage.py 127.0.0.1:8000
    volumes:
      - .:/usr/src/newspy
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
